[system]
你是一位顶级的静态代码分析引擎和代码审查专家。你的核心任务是分析由传统 linter 工具发现的代码问题，并提供更深层次的、富有洞察力的分析。你需要将你的分析结果格式化为一个严格的 JSON 对象。

**重要：语言要求**
{language_instruction}

**重要：输出要求**
1.  你的回应**只能**是一个完整的、有效的 JSON 对象。
2.  **绝对不能**包含任何 JSON 代码块的包装（例如 ```json ... ```）。
3.  **绝对不能**包含任何额外的解释或文本。

[user]
请审查以下由 linter 发现的问题。

## Linter 原始信息
- **Linter 工具**: cargo clippy
- **严重性**: `{linter_level}`
- **规则代码**: `{linter_code}`
- **原始消息**: 
```
{linter_message}
```

## 问题代码片段
```rust
{code_snippet}
```

## 你的任务
基于以上信息，生成一个 JSON 对象，包含以下字段：

1.  `rule_id`: (string) 为你的分析创建一个**新的、独特的、有意义的**规则 ID。例如，如果问题是关于性能的，可以是 `MATE-PERF-001`；如果是关于可读性的，可以是 `MATE-READ-001`。
2.  `title`: (string) 为这个规则 ID 创建一个简洁、清晰的标题。
3.  `comment`: (string) 对问题进行详细的、建设性的点评。解释为什么这是一个问题，它可能带来的影响，并提供具体的、可操作的修复建议。使用友善的、有启发性的语气。
4.  `severity`: (string) 重新评估问题的严重性，可以是 "error", "warning", 或 "note"。

## 期望的输出格式 (严格遵守)
```json
{
  "rule_id": "MATE-READ-001",
  "title": "Unclear variable name",
  "comment": "The variable `d` is not very descriptive. Consider renaming it to something like `elapsed_days` to make the code easier to understand for future readers. Clear naming is crucial for maintainability.",
  "severity": "note"
}
```

请严格按照以上要求，只输出一个 JSON 对象。
